CREATE TABLE IF NOT EXISTS movies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_name TEXT NOT NULL,
    m_image TEXT NOT NULL,
    m_group TEXT NOT NULL,
    m_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS movies_continue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_id INTEGER NOT NULL,
    m_timer INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS series (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_name TEXT NOT NULL,
    m_image TEXT NOT NULL,
    m_group TEXT NOT NULL,
    m_url TEXT NOT NULL,
    m_season INTEGER NOT NULL DEFAULT 0,
    m_episode INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS series_continue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_id INTEGER NOT NULL,
    m_timer INTEGER NOT NULL DEFAULT 0
);